### ISSUE TITLE
library not found using pip

### ISSUE THREAD

**Issue by JoostVisser7** [n8henrie/picam#1]
- **Operating system and version**: Raspbian Stretch kernel 4.14
- **Python version**: 3.5.3
- **picam-motiondetect version**: ???

## My Issue
I can't seem to install the picam lib in the terminal usign pip. I don't know how to install it otherwise

## [WHYT](http://mattgemmell.com/what-have-you-tried)
When using the command pip3 install picam in the terminal it outputs 

Could not find a version that satisfies the requirement picam (from versions: )
No matching distribution found for picam

in red. When I use the command pip3 install https://github.com/n8henrie/picam/ it outputs:

Cannot unpack file /tmp/pip-unpack-e2un_9an/picam (downloaded from /tmp/pip-req-build-kxy4q9lx, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-kxy4q9lx

in red. I've also tried python3.5 -m pip install picam but this gives me the same error as pip3 install picam

**Comment by n8henrie** [comment]
Thanks for your interest.

I never got a *whole* lot done on this repo, and as a result it is not available on PyPI (for instillation with pip), but you're welcome to give it a shot if you'd like.

To install a Python package directly from a git repo like GitHub, you can follow this pattern EDIT: if you have commit privileges and a SSH set up:

```console
$ python3 -m pip install -e git+git@github.com:n8henrie/picam.git#egg=picam
```

where `#egg=picam` shows that `picam` is the name you want to use for the package. Or you can use something like this if you don't have commit privileges and SSH:

```console
$ python3 -m pip install git+https://github.com/n8henrie/picam
```

These seem to change sometimes, so Googling "pip install from GitHub" may be a good idea if it isn't working. [Relevant thread on Reddit.](https://www.reddit.com/r/Python/comments/2crput/how_to_install_with_pip_directly_from_github/)

**Comment by JoostVisser7** [comment]
> Thanks for your interest.
> 
> I never got a _whole_ lot done on this repo, and as a result it is not available on PyPI (for instillation with pip), but you're welcome to give it a shot if you'd like.
> 
> To install a Python package directly from a git repo like GitHub, you can follow this pattern:
> 
> ```
> $ python3 -m pip install -e git+git@github.com:n8henrie/picam.git#egg=picam
> ```
> 
> where `#egg=picam` shows that `picam` is the name you want to use for the package.

I got the following error when trying that (error 128):

Obtaining picam from git+git@github.com:n8henrie/picam.git#egg=picam
  Cloning git@github.com:n8henrie/picam.git to ./src/picam
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is [idk if this has to be private but there is a randomly generated string here].
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q git@github.com:n8henrie/picam.git/home/pi/src/picam" failed with error code 128 in None

**Comment by n8henrie** [comment]
Gah sorry. I tested before posting but forgot it's different depending on whether you have commit privileges and SSH set up. Please see my edit above.
